---

mysql_databases:
  - { name: test1, collation: utf8_general_ci, encoding: utf8, replicate: 0 }

mysql_users:
  - { name: test1, host: "%", password: "{{ mysql_test1_user_password }}", priv: "test1.*:ALL" }

mysql_packages:
  - mariadb
  - mariadb-server
  - MySQL-python

mysql_enablerepo: "epel"
mysql_daemon: mariadb
mysql_slow_query_log_file: /var/log/mariadb/mariadb-slow.log
mysql_log_error: /var/log/mariadb/mariadb.err
mysql_pid_file: /var/run/mariadb/mariadb.pid
